# Generated by Django 4.2.1 on 2023-06-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_items_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Theme',
            new_name='Title',
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name_plural': 'Titles'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='theme',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='theme',
            new_name='title',
        ),
    ]
