# Generated by Django 4.2.1 on 2023-06-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_items_item_rename_theme_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Category',
        ),
    ]
