# Generated by Django 4.2.1 on 2023-06-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_category_options_alter_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='category',
        ),
    ]
