# Generated by Django 4.2.1 on 2023-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='session',
            field=models.CharField(choices=[('M', 'Morning'), ('D', 'Daytime'), ('E', 'Evening')], default='M', max_length=1),
        ),
    ]
