# Generated by Django 4.2.1 on 2023-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_exercise_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='repetitions',
        ),
        migrations.AddField(
            model_name='exercise',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
