# Generated by Django 4.2.1 on 2023-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_content_alter_author_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.CharField(choices=[('SF', 'Science Fiction'), ('MY', 'Mystery'), ('CR', 'Crime'), ('NO', 'Novel'), ('CS', 'Computer Science'), ('NS', 'Natural Sciences')], max_length=2),
        ),
    ]
