# Generated by Django 4.2.1 on 2023-07-02 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('added',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
