# Generated by Django 4.2.1 on 2023-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_product_options_product_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
