# Generated by Django 4.2.1 on 2023-07-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_product_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Product Description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to='products/'),
        ),
    ]
