# Generated by Django 4.2.1 on 2023-07-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
